CREATE TABLE IF NOT EXISTS funcionarios (
    id BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    cpf VARCHAR(11) NOT NULL,
    email VARCHAR(255) NOT NULL,
    nome VARCHAR(255) NOT NULL,
    perfil VARCHAR(255) NOT NULL,
    qtd_horas_almoco FLOAT DEFAULT NULL,
    qtd_horas_trabalho_dia FLOAT DEFAULT NULL,
    senha VARCHAR(255) NOT NULL,
    valor_hora DECIMAL(19,2) DEFAULT NULL,
    empresa_id BIGINT(20) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY(empresa_id) REFERENCES empresas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;