CREATE TABLE IF NOT EXISTS lancamentos (
  id bigint(20) AUTO_INCREMENT PRIMARY KEY,
  data DATETIME NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  descricao VARCHAR(255) DEFAULT NULL,
  localizacao VARCHAR(255) DEFAULT NULL,
  tipo VARCHAR(255) NOT NULL,
  funcionario_id bigint(20) DEFAULT NULL,
  FOREIGN KEY(funcionario_id) REFERENCES funcionarios(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;